# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Blog/Project/zcu104_ps_pl/ps_pl/ps_pl.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
# IP: The module: 'design_1_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Blog/Project/zcu104_ps_pl/ps_pl/ps_pl.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Blog/Project/zcu104_ps_pl/ps_pl/ps_pl.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Blog/Project/zcu104_ps_pl/ps_pl/ps_pl.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Blog/Project/zcu104_ps_pl/ps_pl/ps_pl.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
# IP: The module: 'design_1_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Blog/Project/zcu104_ps_pl/ps_pl/ps_pl.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Blog/Project/zcu104_ps_pl/ps_pl/ps_pl.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Blog/Project/zcu104_ps_pl/ps_pl/ps_pl.gen/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
