# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Blog/Project/zcu104_ps_pl/dut/dut.srcs/sources_1/ip/BRAM_INIT/BRAM_INIT.xci
# IP: The module: 'BRAM_INIT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Blog/Project/zcu104_ps_pl/dut/dut.gen/sources_1/ip/BRAM_INIT/BRAM_INIT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_INIT'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Blog/Project/zcu104_ps_pl/dut/dut.srcs/sources_1/ip/BRAM_INIT/BRAM_INIT.xci
# IP: The module: 'BRAM_INIT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Blog/Project/zcu104_ps_pl/dut/dut.gen/sources_1/ip/BRAM_INIT/BRAM_INIT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_INIT'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
